# _config.yml

# Site settings
title: "Your Project Name"
email: "your-email@example.com"
description: "A short description of your project"
baseurl: "" # leave empty unless your site is hosted in a subfolder
url: "https://your-username.github.io"

# Markdown processor
markdown: kramdown

# Theme
theme: jekyll-theme-primer

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-titles-from-headings

# Exclude unnecessary files/folders
exclude:
  - node_modules
  - backend/node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - package-lock.json
  - yarn.lock
  - package.json
  - .gitignore
  - .github

# Optional: Enable future posts if you use them
future: true
