# _config.yml
title: "Interview-Prep-Ai"
email: "yogendrasinghraghuvanshi75@gmail.com"
description: "A short description of your project"
baseurl: "/Interview-Prep-Ai"
url: "https://yogendra-raghuvanshi.github.io"

markdown: kramdown
theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-titles-from-headings

exclude:
  - node_modules
  - backend/node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - package-lock.json
  - yarn.lock
  - package.json
  - .gitignore
  - .github
  - backend
  - tmp
  - log

future: true
